'use strict';

module.exports = {
	animation: true,
	animationSteps: 60,
	animationEasing: "easeOutQuart",
	showScale: true,
	scaleOverride: false,
	scaleSteps: null,
	scaleStepWidth: null,
	scaleStartValue: null,
	scaleLineColor: "#4E4E4E",
	scaleLineWidth: 2,
	scaleShowLabels: true,
	scaleLabel: "<%= value %>",
	scaleIntegersOnly: true,
	scaleBeginAtZero: false,
	scaleFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
	scaleFontSize: 14,
	scaleFontStyle: "normal",
	scaleFontColor: "#fff",
	responsive: false,
	maintainAspectRatio: false,
	showTooltips: true,
	customTooltips: false,
	tooltipEvents: ["mousemove", "touchstart", "touchmove"],
	tooltipFillColor: "rgba(40, 40, 40, 0.9)",
	tooltipFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
	tooltipFontSize: 13,
	tooltipFontStyle: "normal",
	tooltipFontColor: "#fff",
	tooltipTitleFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
	tooltipTitleFontSize: 12,
	tooltipTitleFontStyle: "bold",
	tooltipTitleFontColor: "#fff",
	tooltipYPadding: 6,
	tooltipXPadding: 6,
	tooltipCaretSize: 8,
	tooltipCornerRadius: 6,
	tooltipXOffset: 10,
	tooltipTemplate: "<%if (label) {%><%= label %><% } %>",
	multiTooltipTemplate: " <%= value %> <%= datasetLabel %>",
	onAnimationProgress: function() {},
	onAnimationComplete: function() {},
	scaleShowLine: true,
	angleShowLineOut: true,
	scaleShowLabels: false,
	scaleBeginAtZero: true,
	angleLineColor: "rgba(0, 0, 2, .2)",
	angleLineWidth: 1,
	pointLabelFontFamily: "'Arial'",
	pointLabelFontStyle: "normal",
	pointLabelFontSize: 11,
	pointLabelFontColor: "#fff",
	pointDot: false,
	pointDotRadius: 1,
	pointDotStrokeWidth: 1,
	pointHitDetectionRadius: 20,
	datasetStroke: false,
	datasetStrokeWidth: 4,
	datasetFill: true
};